# Generated by Django 2.2 on 2020-09-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=25.5),
            preserve_default=False,
        ),
    ]
