# Generated by Django 2.2 on 2020-09-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='percent',
            field=models.FloatField(default=0.05),
            preserve_default=False,
        ),
    ]
