# Generated by Django 2.2 on 2020-09-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('hot', 'hot'), ('new', 'new')], default='hot', max_length=25),
            preserve_default=False,
        ),
    ]
